### ISSUE TITLE
Gear 360 (2016) SM-C200 support?

### ISSUE THREAD

**Issue by neuhaus** [vitorio/gear360-2017-mods#2]
do you think this hack will work on the Gear 360 (2016) (perhaps with minor changes)? Or are the cameras very different?

**Comment by vitorio** [comment]
It looks like something _similar_ might work, but probably not 1:1.  This thread talks about doing related things, but you'd be on your own for figuring out the differences.  I don't have a 2016 camera.  https://github.com/ultramango/gear360reveng/issues/7

Good luck!
