### ISSUE TITLE
How to get live video from camera?

### ISSUE THREAD

**Issue by ivent** [vitorio/gear360-2017-mods#4]
Hi congratulations you did an amazing job, I was wondering if you could create a solution to get the live video from the camera? there are thousands of people who would like to transform this camera into a webcam, if you can display the camera video via html it would be a big step towards being able to make a webcam using the obs software or even our own software in the future and we would give these an extra life amazing cameras that unfortunately samsung abandoned the project.

**Comment by vitorio** [comment]
Thanks, but this isn't a priority for me.  Good luck with alternative solutions!

**Comment by ivent** [comment]
OK thanks
